using '../main.bicep'

param environment = 'dev'
param location = 'eastus'
param workloadName = 'iot-platform'
param iotHubName = 'iot-telemetry-dev-eus-01'
param storageAccountName = 'sttelemetrydeveus01'
param functionAppName = 'func-telemetry-dev-eus-01'
param functionStorageName = 'stfuncdeveus01'
param logAnalyticsName = 'law-shared-dev-eus-01'
param appInsightsName = 'appi-telemetry-dev-eus-01'
param keyVaultName = 'kv-telemetry-dev-eus-01'
param vnetName = 'vnet-iot-dev-eus-01'
param automationAccountName = 'automation-iot-dev-eus-01'
param recoveryVaultName = 'backup-iot-dev-eus-01'
